=== Xispho/NFP121-TP-TitouanHERBAUT/projet-court/src/allumettes/deroulement.dtd
<!ELEMENT deroulement (coup*, gagnant?, tricheur?)>
<!ELEMENT coup EMPTY>
<!ATTLIST coup
        numero CDATA #REQUIRED
        joueur CDATA #REQUIRED
        nbAllumette CDATA #REQUIRED>

<!ELEMENT gagnant (#PCDATA)>
<!ELEMENT tricheur (#PCDATA)>

=== Xispho/NFP121-TP-TitouanHERBAUT/projet-court/src/deroulement.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deroulement SYSTEM "deroulement.dtd">
<deroulement>
  <coup numero="1" joueur="Xavier" nbAllumette="2" />
  <coup numero="2" joueur="Ordinateur" nbAllumette="3" />
  <coup numero="3" joueur="Xavier" nbAllumette="3" />
  <coup numero="4" joueur="Ordinateur" nbAllumette="3" />
  <coup numero="5" joueur="Xavier" nbAllumette="1" />
  <coup numero="6" joueur="Ordinateur" nbAllumette="1" />
  <gagnant>Xavier</gagnant>
</deroulement>

=== Xispho/NFP121-TP-TitouanHERBAUT/projet-court/deroulement.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deroulement SYSTEM "deroulement.dtd">
<deroulement>
  <coup numero="1" joueur="Toto" nbAllumette="1" />
  <coup numero="2" joueur="bot" nbAllumette="3" />
  <coup numero="3" joueur="Toto" nbAllumette="1" />
  <coup numero="4" joueur="bot" nbAllumette="3" />
  <coup numero="5" joueur="Toto" nbAllumette="1" />
  <coup numero="6" joueur="bot" nbAllumette="3" />
  <coup numero="7" joueur="Toto" nbAllumette="1" />
  <gagnant>bot</gagnant>
</deroulement>
